version: '2'

services:
    progrid:
        image: selenium/hub
        container_name: progrid
        privileged: true
        ports:
            - 4444:4444
        environment:
            - GRID_TIMEOUT=240000
            - GRID_BROWSER_TIMEOUT=240000
        networks:
            - custom_grid_internal

    nodechrome:
        image: selenium/node-chrome-debug
        privileged: true
        depends_on:
            - progrid
        ports:
            - 5901:5900
        environment:
            - no_proxy=localhost
            - HUB_PORT_4444_TCP_ADDR=progrid
            - HUB_PORT_4444_TCP_PORT=4444
        networks:
            - custom_grid_internal

    nodefirefox:
        image: selenium/node-firefox-debug
        privileged: true
        depends_on:
            - progrid
        ports:
            - 5900:5900  
        environment:
            - no_proxy=localhost
            - HUB_PORT_4444_TCP_ADDR=progrid
            - HUB_PORT_4444_TCP_PORT=4444
        networks:
            - custom_grid_internal
    
    nodestandalone:
        image: selenium/standalone-chrome-debug
        privileged: true
        depends_on:
            - progrid
        ports:
            - 5902:5900  
        environment:
            - no_proxy=localhost
            - HUB_PORT_4444_TCP_ADDR=progrid
            - HUB_PORT_4444_TCP_PORT=4444
        networks:
            - custom_grid_internal        
 
networks:
    custom_grid_internal: